#Nebula Optimizer Configuration
#Sat Sep 12 11:10:47 BRT 2026
blockCullingDistance=8
debugMode=false
enableAFKDetection=true
enableAIPredictor=true
enableAdaptiveEntityLOD=true
enableAdaptiveFPS=true
enableAdaptiveGUIScale=true
enableAggressiveCulling=true
enableAngleCulling=true
enableAntiGhostBlock=true
enableAudioOptimization=true
enableAutoBoost=true
enableAutoOptimizer=true
enableAutoProfile=true
enableAutoTarget=false
enableAutoTuner=true
enableBatterySaver=true
enableBlockCulling=true
enableBlockEntityCulling=true
enableBottleneckDetection=true
enableChunkLoaderOptimizer=true
enableCombatMode=true
enableCoordinatesDisplay=true
enableDayNightOptimization=true
enableDimensionOptimizer=true
enableDynamicChunkLoading=true
enableDynamicMusic=true
enableDynamicResolution=true
enableDynamicShaders=true
enableEntityCleanup=true
enableEntityCulling=true
enableEntityLOD=true
enableFPSBoost=true
enableFPSHistory=true
enableFPSPredictor=true
enableFarEntitySimplifier=true
enableFasterBlockBreaking=true
enableFireOverlayOpacity=true
enableFramePrediction=true
enableFullbrightToggle=true
enableGameModeDetection=true
enableGameModeProfiles=true
enableGarbageCollection=true
enableIntelligentTicking=true
enableLaunchAcceleration=true
enableLightUpdatesOptimizer=true
enableLightingOptimization=true
enableLogicOptimization=true
enableMemoryManagement=true
enableMemoryOptimizer=true
enableMobilePowerSaving=true
enableMobileTouchControls=true
enableModCompatibility=true
enableNebula=true
enableNetworkOptimization=true
enableNightVisionOptimizer=true
enableOptimizedClouds=true
enableParticleKiller=true
enableParticleLimit=true
enablePerformanceAnalytics=true
enablePerformanceBooster=true
enablePerformanceGraph=true
enablePerformancePrediction=true
enablePerformanceScore=true
enablePumpkinOverlayDisabler=true
enableReduceShakeBobbing=true
enableReducedCollisions=true
enableResourcePreloading=true
enableScreenDimmer=true
enableSelectiveCulling=true
enableSmartAIAssistant=true
enableSmartChunkLoading=true
enableSmartCleanup=true
enableSmartCleanupAdvanced=true
enableSmartEntityAI=true
enableSmartRAMCleaner=true
enableSmartReboot=true
enableSmartSleep=true
enableSmartVentilation=true
enableSmartWeather=true
enableSmoothFPS=true
enableSmoothWorldLoading=true
enableSprintOptimization=true
enableStateBasedRendering=true
enableStateCompression=true
enableTextureStreaming=true
enableTextureUpscaling=true
enableThermalMonitor=true
enableThermalProtection=true
enableThreadPool=true
enableTouchOptimization=true
enableVerticalCulling=true
enableVignetteDisabler=true
enableWaterOptimization=true
enableWorldAnalyzer=true
enableZoomFeature=true
entityRenderDistance=8
entityTickReductionDistance=30
maxParticles=10
maxResolutionPercent=100
minResolutionPercent=60
showFps=true
showPerformanceStats=false
targetFps=60
textureStreamingRadius=30
uiTheme=0
userRenderDistance=4
